# Generated by Django 4.0.8 on 2023-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('gross', models.FloatField()),
                ('tax', models.FloatField()),
                ('net', models.FloatField()),
            ],
        ),
    ]
